import os
from pathlib import Path

# ── Paths ────────────────────────────────────────────────────────────────────
BASE_DIR     = Path(__file__).resolve().parent.parent
MODEL_PATH   = BASE_DIR / "models"          # folder containing config.json, pytorch_model.bin, etc.
UPLOAD_DIR   = BASE_DIR / "uploads"
REPORT_DIR   = BASE_DIR / "reports"

# ── Model settings ────────────────────────────────────────────────────────────
DEVICE       = "cuda" if __import__("torch").cuda.is_available() else "cpu"
IMAGE_SIZE   = 224                          # ViT expects 224×224
LABEL_FAKE   = "FAKE"
LABEL_REAL   = "REAL"

# ── Blob storage ────────────────────────────────────────────────────────────
AZURE_STORAGE_SAS_TOKEN = os.environ.get("AZURE_STORAGE_SAS_TOKEN", "")

# ── Explainability ────────────────────────────────────────────────────────────
ATTENTION_ALPHA   = 0.5                     # heatmap overlay opacity
GRADCAM_ALPHA     = 0.5

# ── Report ────────────────────────────────────────────────────────────────────
REPORT_DISCLAIMER = (
    "This report is generated by an automated AI system and is intended "
    "as investigative support only. It should not be used as sole evidence "
    "in legal or editorial decisions."
)

# Create dirs if missing
for d in (UPLOAD_DIR, REPORT_DIR):
    d.mkdir(parents=True, exist_ok=True)
